services:
  manager:
    container_name: manager
    build: ./
    ports:
      - "8080:8080"
    environment:
      - SPRING_MAIL_HOST=smtp.yandex.ru
      - SPRING_MAIL_PORT=465
      - SPRING_MAIL_USERNAME=test@yandex.ru
      - SPRING_MAIL_PASSWORD=test
      - SPRING_MAIL_PROTOCOL=smtps
      - SPRING_MAIL_ADDRESS=test
      - SPRING_MAIL_TITLE=automated monitoring system
